image: maven:3.5.2-jdk-8

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - deploy


maven_test:
  stage: test
  script: mvn test

maven_package:
  stage: build
  script: mvn package
  artifacts:
    paths:
    - target/portfolio-manager-*.jar

deploy_cf:
  stage: deploy
  image: kramos/cloud-foundry-cli
  script:
    - cf login -a $CF_API -u $CF_USER -p $CF_PASSWORD -o $CF_ORG -s $CF_SPACE
    - cf push
